In [11]:
import numpy as np
 
a = np.array([[1,2,3,4],[4,55,1,2],
              [8,3,20,19],[11,2,22,21]])
m = np.reshape(a,(4, 4))
print(m)
 
# Accessing element
print("\nAccessing Elements")
print(a[1])
print(a[2][0])
 


[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]]

Accessing Elements
[ 4 55  1  2]
8


In [12]:
# Adding Element
m = np.append(m,[[1, 15,13,11]])
# m = np.reshape(m, (4,5))
print("\nAdding Element")
print(m)


Adding Element
[ 1  2  3  4  4 55  1  2  8  3 20 19 11  2 22 21  1 15 13 11]


In [14]:
m = np.reshape(m, (5,4))
print(m)

[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]


In [15]:
# Deleting Element
m = np.delete(m,[1],0)
print("\nDeleting Element")
print(m)


Deleting Element
[[ 1  2  3  4]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]
